[font]
size = 16
[font.normal]
family = "LigaInputMono Nerd Font"
style = "Regular"
[font.bold]
family = "LigaDank Nerd Font"
style = "Bold"
[font.italic]
family = "LigaOperatorMono Nerd Font"
style = "Italic"
[font.bold_italic]
family = "LigaCartographCF Nerd Font"
style = "Italic"

[window]
opacity = 0.9
blur = true
startup_mode = "Maximized"
option_as_alt = "OnlyLeft"

[cursor]
style.blinking = "Always"

[keyboard]
bindings = [{ key = "N", mods = "Control", action = "CreateNewWindow" }]
